### ISSUE TITLE
怎么去标记前景背景呢

### ISSUE THREAD

**Issue by newjavaer** [xuyangcao/random_walker_gui#1]
![QQ图片20200908110449](https://user-images.githubusercontent.com/49930795/92440776-964f4580-f1df-11ea-88a8-4194b2d626e7.png)
是因为我标记的问题吗还是效果就是这样？

**Comment by xuyangcao** [comment]
> ![QQ图片20200908110449](https://user-images.githubusercontent.com/49930795/92440776-964f4580-f1df-11ea-88a8-4194b2d626e7.png)
> 是因为我标记的问题吗还是效果就是这样？

The random walk algorithm is sensitive to markers, I updated a simple doc on how to label markers on the README file. 

the marker can be as follows:

![marker](https://user-images.githubusercontent.com/12201001/92671341-9880e380-f348-11ea-8fc0-3d942b156947.png)

the corresponding result:

![result](https://user-images.githubusercontent.com/12201001/92671390-b2bac180-f348-11ea-97f1-cb751ee13171.png)
